### ISSUE TITLE
Matlab toolbox required for SIFT

### ISSUE THREAD

**Issue by Sumire0612** [sccn/SIFT#10]
Dear Professor in Charge

I am currently using the most standard Matlab environment. I have just tried to use SIFT for signal source estimation and received an error saying that I need to add Matlab's "Statistics and Machine Learning Toolbox". If you need to add a lot, this is the environment where SIFT cannot be used. Please let me know what optional toolboxes are needed.

Sincerely

**Comment by arnodelorme** [comment]
I think just the stat and the signal processing toolbox.

**Comment by Sumire0612** [comment]
Dear Professor

Thank you for your prompt response.
I understand about the toolbox.

Sincerely yours
