### ISSUE TITLE
A question about movie output

### ISSUE THREAD

**Issue by cuic0808** [sccn/SIFT#4]
Hi everyone！
When I used STFT ourput movie, I can only export image, and when I output movie, always error (the second picture) report. I didn't find how to set movieOpts, I want to ask how to solve this?

![图片](https://user-images.githubusercontent.com/60568603/113093179-fb24c880-9221-11eb-8984-04622bf086d9.png)
![图片](https://user-images.githubusercontent.com/60568603/113093372-5951ab80-9222-11eb-93e0-c11ddea42779.png)

**Comment by arnodelorme** [comment]
I would try calling the function from the command line.

**Comment by cuic0808** [comment]
> 
> 
> I would try calling the function from the command line.

Dear Dr.Delorme
Thank you very much for your reply. I'm sorry that my codeing level is poor, and I can't run the sample code (maybe not suitable for new version). I was wonder if you could kindly send some output code to me🙏.

**Comment by cuic0808** [comment]
> 
> 
> I would try calling the function from the command line.

Dear Dr.Delorme
Thank you very much for your reply. I'm sorry that my coding level is poor, and I can't run the sample code (maybe not suitable for new version). I was wonder if you could kindly send some output code to me🙏.

**Comment by arnodelorme** [comment]
Unfortunately, not enough time to do that. Look up the function help message. Cheers

**Comment by cuic0808** [comment]
> 
> 
> Unfortunately, not enough time to do that. Look up the function help message. Cheers

Thank you again. I will try it😄.
